### ISSUE TITLE
[Feature Request] Build Conda Package

### ISSUE THREAD

**Issue by KumaTea** [KurimuzonAkuma/pyrogram#140]
### Checklist

- [x] I believe the idea is awesome and would benefit the framework
- [x] I have searched in the issue tracker for similar requests, including closed ones

### Description

Firstly thank you for bring Pyrogram to a new life.

Since it is a `noarch` package, it should be not so hard to build and maintain a `conda` package. A `meta.yaml` file could be:

```yaml
{% set name = "pyrogram" %}
{% set pypiname = "kurigram" %}
{% set version = "2.1.38" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  sha256: d26fe47eaa8b29e494cceda6742045b96ff2d3f429fd28c2bfb25b3216eb8873
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - pyaes
    - pysocks
    - python >=3.7

test:
  commands:
    - pytest -vv tests
    - pip check
  imports:
    - pyrogram
  requires:
    - pip
    - pytest
    - pytest-asyncio
  source_files:
    - tests

about:
  dev_url: https://github.com/KurimuzonAkuma/pyrogram
  home: https://github.com/KurimuzonAkuma
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.lesser
    - NOTICE
  summary: Elegant, modern and asynchronous Telegram MTProto API framework in Python for users and bots

extra:
  recipe-maintainers:
    - kuma
```

And we can easily build the package like:

[pyrogram-2.1.38-py_0.conda.zip](https://github.com/user-attachments/files/18760950/pyrogram-2.1.38-py_0.conda.zip)

---

The conda ecosystem is nice for machine learning and scientific research which manage the dependencies and environment neatly. Wish you could consider this feature by GitHub Actions or welcome pull requests :)
